apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-web-apache
 namespace: my-ns
 labels:
   app: apache
spec:
 replicas: 3
 selector:
   matchLabels:
     app: apache
 template:
   metadata:
     labels:
       app: apache
   spec:
     containers:
     - name: apache
       image: httpd:latest
       ports:
       - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: my-ns
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001


---
apiVersion: v1
kind: Service
metadata:
  name: clusterip
  namespace: my-ns
spec:
  type: ClusterIP
  selector:
    app: apache
  clusterIP: 10.96.1.10
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80