apiVersion: batch/v1
kind: Job
metadata:
  name: node-port
spec:
  template:
    spec:
      containers:
      - name: node-port
        image: curlimages/curl:latest
        command: ['curl', '10.200.0.3:30001']
      restartPolicy: OnFailure